### ISSUE TITLE
Crash in DirectoryAdapter

### ISSUE THREAD

**Issue by mostafaimran** [nbsp-team/MaterialFilePicker#102]
`java.lang.NoSuchMethodError: No virtual method placeholder(I)Lcom/bumptech/glide/f/f; in class Lcom/bumptech/glide/f/f; or its super classes (declaration of 'com.bumptech.glide.f.f' appears in /data/app/com.cloudapper.android-1/base.apk)
        at com.nbsp.materialfilepicker.ui.b.a(DirectoryAdapter.java:5)
        at com.nbsp.materialfilepicker.ui.b.b(DirectoryAdapter.java:1)
        at androidx.recyclerview.widget.RecyclerView$a.a(RecyclerView.java:1)
        at androidx.recyclerview.widget.RecyclerView$a.a(RecyclerView.java:14)
        at androidx.recyclerview.widget.RecyclerView$o.a(RecyclerView.java:8)
        at androidx.recyclerview.widget.RecyclerView$o.a(RecyclerView.java:73)
        at androidx.recyclerview.widget.RecyclerView$o.b(RecyclerView.java:1)
        at androidx.recyclerview.widget.RecyclerView$o.d(RecyclerView.java:11)
        at androidx.recyclerview.widget.LinearLayoutManager$c.a(LinearLayoutManager.java:4)
        at androidx.recyclerview.widget.LinearLayoutManager.a(LinearLayoutManager.java:150)
        at androidx.recyclerview.widget.LinearLayoutManager.a(LinearLayoutManager.java:137)
        at androidx.recyclerview.widget.LinearLayoutManager.e(LinearLayoutManager.java:59)
        at androidx.recyclerview.widget.RecyclerView.B(RecyclerView.java:8)
        at androidx.recyclerview.widget.RecyclerView.c(RecyclerView.java:31)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:2)
        at android.view.View.layout(View.java:16639)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16639)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16639)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1735)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1579)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1488)
        at android.view.View.layout(View.java:16639)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16639)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1735)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1579)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1488)
        at android.view.View.layout(View.java:16639)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16639)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1735)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1579)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1488)
        at android.view.View.layout(View.java:16639)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2934)
        at android.view.View.layout(View.java:16639)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2179)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1939)`

**Comment by dimorinny** [comment]
It seems like that particular problem isn't related to this library. We don't use glide at all. Are you sure you've applied correct mappings to this stack trace?
