### ISSUE TITLE
UnsupportedOperationException: Failed to resolve attribute at index 1: TypedValue{t=0x2/d=0x7f0300b7 a=7 r=0x7f050030

### ISSUE THREAD

**Issue by manassharma07** [nbsp-team/MaterialFilePicker#123]
I have been using this library for years without any problems. But unfortunately today while working on a new project I used the latest version of the library but it doesn't work unfortunately. Any ideas?

```
Process: com.example.opengl3, PID: 15818
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.opengl3/com.nbsp.materialfilepicker.ui.FilePickerActivity}: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 1: TypedValue{t=0x2/d=0x7f0300b7 a=7 r=0x7f050030}
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 1: TypedValue{t=0x2/d=0x7f0300b7 a=7 r=0x7f050030}
        at android.content.res.TypedArray.getColor(TypedArray.java:528)
        at android.app.Activity.onApplyThemeResource(Activity.java:5104)
        at android.view.ContextThemeWrapper.initializeTheme(ContextThemeWrapper.java:216)
        at android.view.ContextThemeWrapper.setTheme(ContextThemeWrapper.java:147)
        at android.app.Activity.setTheme(Activity.java:5082)
        at androidx.appcompat.app.AppCompatActivity.setTheme(AppCompatActivity.java:120)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3415)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

**Comment by naimur978** [comment]
Add these lines inside the "resources" of your colors.xml file

`<color name="colorPrimary">#3F51B5</color>`
`<color name="colorPrimaryDark">#303F9F</color>`
`<color name="colorAccent">#FF4081</color>`

**Comment by arteaprogramar** [comment]
Hey guy you can check this!

https://github.com/arteaprogramar/Android-MaterialFilePicker
