### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by rt1shnik** [nbsp-team/MaterialFilePicker#24]
Fast open/close activity.

```
java.lang.IllegalStateException: Activity has been destroyed
at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1352)
at android.app.BackStackRecord.commitInternal(BackStackRecord.java:597)
at android.app.BackStackRecord.commit(BackStackRecord.java:575)
at com.nbsp.materialfilepicker.ui.FilePickerActivity.addFragmentToBackStack(FilePickerActivity.java:136)
at com.nbsp.materialfilepicker.ui.FilePickerActivity.handleFileClicked(FilePickerActivity.java:180)
at com.nbsp.materialfilepicker.ui.FilePickerActivity.access$000(FilePickerActivity.java:24)
at com.nbsp.materialfilepicker.ui.FilePickerActivity$1.run(FilePickerActivity.java:173)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:212)
at android.app.ActivityThread.main(ActivityThread.java:5135)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:878)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by lukaville** [comment]
Hi! Can you make a pull request with fixes? Thanks.
