### ISSUE TITLE
Can't use ARG_FILE_FILTER as documented

### ISSUE THREAD

**Issue by kjkrum** [nbsp-team/MaterialFilePicker#34]
The `ARG_FILE_FILTER` shown in the readme doesn't exist.  Apparently it was replaced by `ARG_FILTER`.  But it doesn't work.

```
intent.putExtra(FilePickerActivity.ARG_FILTER, Pattern.compile(".*\\.txt$"));
```
...results in this crash:

```
FATAL EXCEPTION: main
 Process: com.chalcodes.maps, PID: 5164
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chalcodes.maps/com.nbsp.materialfilepicker.ui.FilePickerActivity}: java.lang.ClassCastException: java.util.regex.Pattern cannot be cast to com.nbsp.materialfilepicker.filter.CompositeFilter
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2339)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)
     at android.app.ActivityThread.access$800(ActivityThread.java:155)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:135)
     at android.app.ActivityThread.main(ActivityThread.java:5343)
     at java.lang.reflect.Method.invoke(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:372)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
  Caused by: java.lang.ClassCastException: java.util.regex.Pattern cannot be cast to com.nbsp.materialfilepicker.filter.CompositeFilter
     at com.nbsp.materialfilepicker.ui.FilePickerActivity.initArguments(FilePickerActivity.java:62)
     at com.nbsp.materialfilepicker.ui.FilePickerActivity.onCreate(FilePickerActivity.java:47)
     at android.app.Activity.performCreate(Activity.java:6010)
     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413) 
     at android.app.ActivityThread.access$800(ActivityThread.java:155) 
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317) 
     at android.os.Handler.dispatchMessage(Handler.java:102) 
     at android.os.Looper.loop(Looper.java:135) 
     at android.app.ActivityThread.main(ActivityThread.java:5343) 
     at java.lang.reflect.Method.invoke(Native Method) 
     at java.lang.reflect.Method.invoke(Method.java:372) 
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700) 
```

**Comment by lukaville** [comment]
Sorry. It's a bug. As workaround you can use MaterialFilePicker builder class for now:
```new MaterialFilePicker()
    .withActivity(this)
    .withRequestCode(1)
    .withFilter(Pattern.compile(".*\\.txt$"))
    .start();```

**Comment by Dereckz** [comment]
How to select two specific file types?

Example:
".*\\.pdf$"
".*\\.doc$"
