### ISSUE TITLE
Crash when activity launched with startActivityForResult() without ARG_CLOSEABLE extra

### ISSUE THREAD

**Issue by gbak** [nbsp-team/MaterialFilePicker#79]
Launching activity with the Intent/StartActivity will crash the app with a null pointer exception

```
02-08 15:45:36.311 27680 27680 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
02-08 15:45:36.311 27680 27680 E AndroidRuntime: 	at com.nbsp.materialfilepicker.ui.FilePickerActivity.onCreateOptionsMenu(FilePickerActivity.java:187)
02-08 15:45:36.311 27680 27680 E AndroidRuntime: 	at android.app.Activity.onCreatePanelMenu(Activity.java:3396)
02-08 15:45:36.311 27680 27680 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:321)
```

Launched with:
```
       val intent = Intent( activity, FilePickerActivity::class.java)
        intent.putExtra(FilePickerActivity.ARG_FILTER, Pattern.compile(".*\\.txt$"))
        startActivityForResult(intent, 1)
 ```

FilePickerActivity.java contains a Boolean which is never initialized if ARG_CLOSEABLE is never supplied as an Intent Extra.

**Comment by Rhygon** [comment]
Surely deserves mentioned in on the main page, also fell foul to colorAccent, and colorPrimary etc, needing to be present in main apps resources, took all afternoon.
