### ISSUE TITLE
Crash on theme Theme.AppCompat.Light.NoActionBar

### ISSUE THREAD

**Issue by vokrut** [nbsp-team/MaterialFilePicker#83]
It's crashed, i think maybe it's needed to set some attribute in my theme?

`Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 6: TypedValue{t=0x2/d=0x7f040098 a=4 r=0x7f06003f}
                                                               at android.content.res.TypedArray.getColorStateList(TypedArray.java:498)
                                                               at android.widget.TextView.<init>(TextView.java:824)
                                                               at android.widget.TextView.<init>(TextView.java:735)
                                                               at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:76)
                                                               at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:72)
                                                               at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:68)
                                                               at android.support.v7.widget.Toolbar.setTitle(Toolbar.java:754)
                                                               at android.support.v7.widget.ToolbarWidgetWrapper.setTitleInt(ToolbarWidgetWrapper.java:261)
                                                               at android.support.v7.widget.ToolbarWidgetWrapper.setWindowTitle(ToolbarWidgetWrapper.java:243)
                                                               at android.support.v7.app.ToolbarActionBar.<init>(ToolbarActionBar.java:72)
                                                               at android.support.v7.app.AppCompatDelegateImplV9.setSupportActionBar(AppCompatDelegateImplV9.java:217)
                                                               at android.support.v7.app.AppCompatActivity.setSupportActionBar(AppCompatActivity.java:129)
                                                               at com.nbsp.materialfilepicker.ui.FilePickerActivity.initToolbar(FilePickerActivity.java:109)
                                                               at com.nbsp.materialfilepicker.ui.FilePickerActivity.onCreate(FilePickerActivity.java:61)
                                                               at android.app.Activity.performCreate(Activity.java:6361)
                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2532)
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2667) 
                                                               at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1501) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                               at android.os.Looper.loop(Looper.java:207) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5811) 
                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:802) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:692) `

**Comment by lingyfh** [comment]
how did you fix the problem. I have the same problem. @vokrut

**Comment by wankey** [comment]
have the same problem on 2021

**Comment by u-barnwal** [comment]
Check this answer here: https://github.com/nbsp-team/MaterialFilePicker/issues/123#issuecomment-735373141
