### ISSUE TITLE
Issue inflating layouts when using version greater than 1.2

### ISSUE THREAD

**Issue by Rhygon** [nbsp-team/MaterialFilePicker#92]
Getting a issue with inflation of Buttons, when I used version 1.4 and above. I read a few things about styles causing issues. Not sure if anyone had this problem.

Full exception stack:
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.##, PID: 27368
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.##/com.##.ui.MainActivity}: android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class Button
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2984)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
                      at android.app.ActivityThread.-wrap14(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6776)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
                   Caused by: android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class Button
                   Caused by: android.view.InflateException: Binary XML file line #6: Error inflating class Button
                   Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 6: TypedValue{t=0x2/d=0x7f03004e a=3 r=0x7f05002f}
                      at android.content.res.TypedArray.getColorStateList(TypedArray.java:545)
                      at android.widget.TextView.<init>(TextView.java:1118)
                      at android.widget.Button.<init>(Button.java:113)
                      at android.widget.Button.<init>(Button.java:106)
                      at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:66)
                      at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:62)
                      at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:109)
                      at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1029)
                      at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1087)
                      at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:47)
                      at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:193)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:525)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
                      at com.##.ui.MainFragment.onCreateView(MainFragment.java:79)
                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                      at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                      at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                      at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
                      at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
                      at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
                      at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
                      at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1256)
                      at android.app.Activity.performStart(Activity.java:6972)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2937)
E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
                      at android.app.ActivityThread.-wrap14(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6776)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)

**Comment by Rhygon** [comment]
Hi,

Ok so for some reason, my styles.xml class for AppTheme had the android:colorAccent set to @color/ColorAccent which is a color in this libraries resources. And it's a bright pink.

For whatever reason, with 1.2 it does not complain builds, but with any later version, the application crashes as above.

So it's not the library just someone was using resources unnecessarily for one, and for some reason may it could not longer find that resource in the library.
