### ISSUE TITLE
App crashing randomly

### ISSUE THREAD

**Issue by Devandroid2006** [nbsp-team/MaterialFilePicker#97]
### App crashes randomly.

Please check the below logs for two sessions.

///////////////////////////////////////

### - Crash logs 1

java.lang.OutOfMemoryError
	at java.util.ArrayList.add(ArrayList.java:118)
	at com.nbsp.materialfilepicker.ui.FilePickerActivity.initBackStackState(FilePickerActivity.java:155)
	at com.nbsp.materialfilepicker.ui.FilePickerActivity.onCreate(FilePickerActivity.java:62)
	at android.app.Activity.performCreate(Activity.java:5327)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2151)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2236)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3727)
	at android.app.ActivityThread.access$900(ActivityThread.java:138)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5034)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:788)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:604)
	at dalvik.system.NativeStart.main(Native Method)

///////////////////////////////////////

### - Crash logs 2

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nbsp.materialfilepicker.ui.FilePickerActivity}: java.lang.RuntimeException: Failed to resolve attribute at index 210
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
	at android.app.ActivityThread.access$800(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
Caused by: java.lang.RuntimeException: Failed to resolve attribute at index 210
	at android.content.res.TypedArray.getColor(TypedArray.java:401)
	at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:3477)
	at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3677)
	at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1943)
	at android.support.v7.app.AppCompatDelegateImplV9.createSubDecor(AppCompatDelegateImplV9.java:374)
	at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:323)
	at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
	at com.nbsp.materialfilepicker.ui.FilePickerActivity.onCreate(FilePickerActivity.java:57)
	at android.app.Activity.performCreate(Activity.java:6042)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
	... 10 more

**Comment by zeevy** [comment]
#98

**Comment by dimorinny** [comment]
We fixed it on the 1.9 version. Please check. Thank you for the report!
