### ISSUE TITLE
Fatal Exception: java.lang.OutOfMemoryError 

### ISSUE THREAD

**Issue by zeevy** [nbsp-team/MaterialFilePicker#98]
Fatal Exception: java.lang.OutOfMemoryError
FilePickerActivity.java line 155
com.nbsp.materialfilepicker.ui.FilePickerActivity.initBackStackState 
Failed to allocate a 420546432 byte allocation with 25116672 free bytes and 241MB until OOM, max allowed footprint 309232192, growth limit 536870912

Device
Brand: HUAWEI
Model: EML-L29
Orientation: Portrait
RAM free: 1.3 GB
Disk free: 40.42 GB 

Operating System
Version: 8.1.0
Orientation: Portrait
Rooted: No 

I hope this information is enough.

```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 420546432 byte allocation with 25116672 free bytes and 241MB until OOM, max allowed footprint 309232192, growth limit 536870912
       at java.util.Arrays.copyOf(Arrays.java:3139)
       at java.util.Arrays.copyOf(Arrays.java:3109)
       at java.util.ArrayList.grow(ArrayList.java:275)
       at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:249)
       at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:241)
       at java.util.ArrayList.add(ArrayList.java:467)
       at com.nbsp.materialfilepicker.ui.FilePickerActivity.initBackStackState(FilePickerActivity.java:155)
       at com.nbsp.materialfilepicker.ui.FilePickerActivity.onCreate(FilePickerActivity.java:62)
       at android.app.Activity.performCreate(Activity.java:7362)
       at android.app.Activity.performCreate(Activity.java:7353)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1219)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3126)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3284)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5336)
       at android.app.ActivityThread.-wrap19(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1900)
       at android.os.Handler.dispatchMessage(Handler.java:109)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7383)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
```

```
Queue
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:2163)
       at sun.misc.Unsafe.park(Unsafe.java:358)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059)
       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:548)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.performOperation(DependencyPriorityBlockingQueue.java:197)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.get(DependencyPriorityBlockingQueue.java:236)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:65)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:46)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1087)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:784)
```

```
Queue
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:2163)
       at sun.misc.Unsafe.park(Unsafe.java:358)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059)
       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:548)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.performOperation(DependencyPriorityBlockingQueue.java:197)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.get(DependencyPriorityBlockingQueue.java:236)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:65)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:46)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1087)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:784)
```

```
FirebaseInstanceId
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:2163)
       at sun.misc.Unsafe.park(Unsafe.java:358)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1120)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1087)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
       at java.lang.Thread.run(Thread.java:784)
```
```
Thread-16
       at android.hardware.usb.UsbDeviceConnection.native_request_wait(UsbDeviceConnection.java)
       at android.hardware.usb.UsbDeviceConnection.requestWait(UsbDeviceConnection.java:291)
       at com.felhr.usbserial.UsbSerialDevice$WorkerThread.run(UsbSerialDevice.java:326)
```

**Comment by dimorinny** [comment]
We've already fixed it. Check 1.9 version. Thank you for the report!
